### PR TITLE
(GH-2) First version based on Cake.Prca

### LINKED ISSUE #2: First version based on Cake.Prca
Release first version based on Cake.Prca

### PR DESCRIPTION
**Pull request by pascalberger**
First version based on Cake.Prca

Fixes #2

### CODE REVIEW

**Comment by pascalberger** [comment]
@gep13 Any idea about this: https://ci.appveyor.com/project/cakecontrib/cake-issues/build/0.1.0-PullRequest.1+2.build.4#L513 ?

**Comment by devlead** [comment]
Perhaps as VS2017 os image here
https://github.com/cake-contrib/Cake.Issues/blob/c4fc526a2da6141cb127b3edb48061fb6e2914aa/.appveyor.yml

**Comment by gep13** [comment]
@pascalberger I think @devlead is correct here.  I think it is the AppVeyor Image that needs to be bumped.

**Comment by pascalberger** [comment]
@devlead @gep13 With the `Visual Studio 2017` image the following error appears

```
Warning: Do not know VsVersionToYearString for VS version 15.3.
```

https://ci.appveyor.com/project/cakecontrib/cake-issues/build/0.1.0-PullRequest.1+2.build.6#L476

**Comment by devlead** [comment]
Maybe need to bump tool to https://www.nuget.org/packages/JetBrains.ReSharper.CommandLineTools/2017.1.20170613.162720

**Pull request merged**
